name: flutter_citadel
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=3.1.0 <4.0.0"
  flutter: ">=3.7.0"


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: 1.0.6

  # Localization
  flutter_localizations:
    sdk: flutter

  # BSD
  intl: 0.18.1

  # Network
  # MIT
  dio: 5.4.0

  # Local storage
  # Apache 2.0
  hive_flutter: 1.1.0
  # BSD-2-Clause
  flutter_secure_storage: 9.0.0

  # UI
  # MIT
  flutter_svg: 2.0.9
  # MIT
  dotted_border: 2.1.0
  # MIT
  step_progress_indicator: 1.0.2
  # MIT
  flutter_staggered_grid_view: 0.7.0
  # MIT
  multi_split_view: 2.4.0
  # MIT
  flutter_chat_ui: 1.6.12

  uuid: 4.2.2

#  # Firebase
#  firebase_core: 2.25.4
#  # BSD
#  # todo starter: FCM background messages on iOS need additional setup with apple developer account
#  firebase_messaging: 14.7.8
#  # BSD
#  firebase_crashlytics: 3.4.8
#  # BSD
#  firebase_analytics: 10.8.5
  # BSD
  flutter_local_notifications: 16.3.2

  # Other
  # BSD
  share_plus: 7.2.2
  # BSD
  package_info: 2.0.2
  # BSD
  rxdart: 0.27.7
  # BSD
  synchronized: 3.1.0+1

dev_dependencies:
#  flutter_test:
#    sdk: flutter
  flutter_lints: 3.0.1
  # Apache 2.0
  hive_generator: 2.0.1
  # BSD
  build_runner: 2.4.8
  # Extensions
  # Apache 2.0
  dartx: 1.2.0

flutter_intl:
  enabled: true
  main_locale: en_US

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/icons/
    - assets/data/
    - assets/data/classic/
    - assets/data/classic/districts/
    - assets/data/classic/heroes/
    - assets/data/delux/
    - assets/data/delux/districts/
    - assets/data/delux/heroes/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700

